# Build using: docker build -f Dockerfile.gocd-agent -t gocd-agent .
FROM phusion/baseimage:0.9.16
MAINTAINER Aravind SV <arvind.sv@gmail.com>

RUN rm -rf /etc/service/sshd /etc/my_init.d/00_regen_ssh_host_keys.sh
RUN apt-get update && \
    apt-get install -y -q unzip openjdk-7-jre-headless git npm && \
    ln -s /usr/bin/nodejs /usr/bin/node && \
    sudo apt-get install wget && \
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash - && \
    sudo apt-get install -y nodejs && \
    npm install -g grunt-cli && \
    wget -qO- https://get.docker.com/ | sh && \
    sudo usermod -aG docker go

RUN mkdir /etc/service/go-agent
ADD gocd-agent/go-agent-start.sh /etc/service/go-agent/run

ADD http://download.go.cd/gocd-deb/go-agent-15.1.0-1863.deb /tmp/go-agent.deb

WORKDIR /tmp
RUN dpkg -i /tmp/go-agent.deb
RUN sed -i -e 's/DAEMON=Y/DAEMON=N/' /etc/default/go-agent /etc/default/go-agent

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /var/go/.ssh
RUN chown -R go:go /var/go/.ssh
RUN chmod -R 700 /var/go/.ssh
VOLUME ["/var/go/.ssh"]

CMD ["/sbin/my_init"]
